API_URL: "localhost:8888"
DB_HOST: "luxamrown-db-sgp-do-user-11779932-0.b.db.ondigitalocean.com"
DB_PORT: "25060"
DB_NAME: "luxamrown-bankapp"
DB_USER: "doadmin2"
DB_PASSWORD: "AVNS_hxQ84ERlgwf-5645l3K"